//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardingCard
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> DateLastOperation { get; set; }
        public Nullable<int> BoardingCardStatus { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> FlightId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual CashBox CashBox { get; set; }
    }
}
