//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.BoardingCards = new HashSet<BoardingCard>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public byte FlightStatus { get; set; }
        public int FlightNumber { get; set; }
        public int Direct { get; set; }
        public byte Terminal { get; set; }
        public string FromPlace { get; set; }
        public string ToPlace { get; set; }
        public Nullable<int> AirplaneId { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardingCard> BoardingCards { get; set; }
        public virtual TimeTable TimeTable { get; set; }
    }
}
