//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ExpectedDepartureTime { get; set; }
        public Nullable<System.DateTime> ExpectedArrivalTime { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
